name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish-github-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16.x
        registry-url: https://npm.pkg.github.com/
        scope: '@VashonG'
    - run: npm ci
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
